extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'immich-server'
        scrape_interval: 15s
        static_configs:
        - targets: ['localhost:8081']
      - job_name: 'node-exporter'
        scrape_interval: 15s
        static_configs:
        - targets: ['localhost:9100']
      - job_name: 'otelcol'
        scrape_interval: 15s
        static_configs:
        - targets: ['localhost:8888']

exporters:
  otlphttp:
    endpoint: http://10.64.223.160:4318

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [otlphttp]
  extensions: [health_check]
  telemetry:
    metrics:
      level: normal
