{
 "title": "Immich",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Immich version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "target_info", "legendFormat": "{{service_version}}" }
   ]
  },
  {
   "title": "User count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_memory_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(system_memory_usage)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_usage{system_memory_state=\"used\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_utilization{system_memory_state=\"used\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API latency (p95)",
   "type": "timeseries",
   "description": "amount of CPU usage over time",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{net_host_port=\"2283\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(system_cpu_utilization{system_cpu_state=\"idle\"}))",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Used memory",
   "type": "timeseries",
   "description": "Free memory over time",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_memory_usage{system_memory_state=\"used\"}",
     "legendFormat": "{{system_memory_state}}"
    }
   ]
  },
  {
   "title": "API requests (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_count_total[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API requests (1w)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_count_total[1w]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory by state",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_memory_usage", "legendFormat": "{{system_memory_state}}" }
   ]
  },
  {
   "title": "API requests (4w)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_count_total[4w]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API requests (1y)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_count_total[1y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful responses (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_response_success_count_total[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful responses (1w)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_response_success_count_total[1w]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU by state",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_utilization", "legendFormat": "{{process_cpu_state}}" }
   ]
  },
  {
   "title": "Successful responses (4w)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_response_success_count_total[4w]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful responses (1y)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_response_success_count_total[1y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network throughput (5m)",
   "type": "timeseries",
   "description": "amount of photos over time",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(system_network_io_total[$__rate_interval])) by (network_io_direction)",
     "legendFormat": "{{network_io_direction}}"
    }
   ]
  },
  {
   "title": "ML tick latency (p95)",
   "type": "timeseries",
   "description": "amount of photos over time",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(immich_machine_learning_repository_tick_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes served (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_response_size_sum[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes served (1w)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_response_size_sum[1w]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network IO by direction",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_network_io_total) by (network_io_direction)",
     "legendFormat": "{{network_io_direction}}"
    }
   ]
  },
  {
   "title": "Bytes served (4w)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_response_size_sum[4w]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes served (1y)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_response_size_sum[1y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job queue latency (p95)",
   "type": "timeseries",
   "description": "amount of videos over time",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(immich_job_repository_queue_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB with_lock latency (p95)",
   "type": "timeseries",
   "description": "amount of videos over time",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(immich_database_repository_with_lock_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}